### ISSUE TITLE
Lets make it work

### ISSUE THREAD

**Issue by vseehausen** [svrcekmichal/create-react-app#1]
Hey, thank you very much for your work! I hope, this will be a sufficient workaround for the integration of Relay into CRA.

So. I created a App with CRA. Added this script. Removed the old react-script from the package.json. Created a .env and installed react-relay.

On yarn start I get this error:

```
yarn start --verbose
yarn start v0.18.1
$ react-scripts start 
Relay support - graphql configured successfully
[SyntaxError: Unexpected token B]

verbose Error: Command failed with exit code 1.
    at MessageError (/usr/share/yarn/lib/errors.js:7:26)
    at /usr/share/yarn/lib/util/execute-lifecycle-script.js:201:15
    at throw (native)
    at step (/usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/share/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:30:13
    at run (/usr/share/yarn/node_modules/core-js/library/modules/es6.promise.js:87:22)
    at /usr/share/yarn/node_modules/core-js/library/modules/es6.promise.js:100:28
    at flush (/usr/share/yarn/node_modules/core-js/library/modules/_microtask.js:18:9)
    at doNTCallback0 (node.js:428:9)
    at process._tickCallback (node.js:357:13)
error Command failed with exit code 1.
```

**Comment by svrcekmichal** [comment]
Ou, never tried with yarn, will try as soon as i can

**Comment by vseehausen** [comment]
Ah ok, my mistake.

It seemed, that my graphql server didn't supply the IntrospectionQuery.

I tested it with another server and it works. Seems, that your script is working. Awesome, thank you very much!
